#!/usr/bin/python3

GRID_NETWORK_CAPACITY = 3000
GRID_NODES = GRID_NETWORK_CAPACITY/10 # GRID_NODES are 1/10th of the network

print(GRID_NODES)

#ENERGY_GENERATED
EG
#GRID_BATTERY_CAPACITY
GBC
#NODE_BATTERY_CAPACITY
NBC
#GRID_ENERGY_LOSS
GEL
#GRID_BATTERY_CAPACITY_LOSS_RATE
GBCLR
#GRID_NETWORK_HEALTH
GNH