#!/usr/bin/python3

GRID_NETWORK_CAPACITY = 3000
GRID_NODES = GRID_NETWORK_CAPACITY/10 # GRID_NODES are 1/10th of the network

print(GRID_NODES)

#   ENERGY_GENERATED

#   GRID_BATTERY_CAPACITY

#   NODE_BATTERY_CAPACITY

#   GRID_ENERGY_LOSS

#   GRID_BATTERY_CAPACITY_LOSS

#   GRID_NETWORK_HEALTH